# coding: utf-8

"""
    DataForSEO API documentation

    DataForSEO API is the starting point on your journey towards building powerful SEO software. With DataForSEO you can get all the data you need to build an efficient application while also saving your time and budget. DataForSEO API is using the REST technology for interchanging data between your application and our service. The data exchange is made through the widely used HTTP protocol, which allows applying our API to almost all programming languages.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel
from typing import Any, ClassVar, Dict, List, Optional
from dataforseo_client.models.appendix_info import AppendixInfo
from typing import Optional, Set
from typing_extensions import Self

class AppendixDataforseoTrendsKeywordsDataLimitsRatesDataInfo(BaseModel):
    """
    AppendixDataforseoTrendsKeywordsDataLimitsRatesDataInfo
    """ # noqa: E501
    explore: Optional[AppendixInfo] = None
    subregion_interests: Optional[AppendixInfo] = None
    demography: Optional[AppendixInfo] = None
    merged_data: Optional[AppendixInfo] = None
    __properties: ClassVar[List[str]] = ["explore", "subregion_interests", "demography", "merged_data"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AppendixDataforseoTrendsKeywordsDataLimitsRatesDataInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of explore
        if self.explore:
            _dict['explore'] = self.explore.to_dict()
        # override the default output from pydantic by calling `to_dict()` of subregion_interests
        if self.subregion_interests:
            _dict['subregion_interests'] = self.subregion_interests.to_dict()
        # override the default output from pydantic by calling `to_dict()` of demography
        if self.demography:
            _dict['demography'] = self.demography.to_dict()
        # override the default output from pydantic by calling `to_dict()` of merged_data
        if self.merged_data:
            _dict['merged_data'] = self.merged_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AppendixDataforseoTrendsKeywordsDataLimitsRatesDataInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "explore": AppendixInfo.from_dict(obj["explore"]) if obj.get("explore") is not None else None,
            "subregion_interests": AppendixInfo.from_dict(obj["subregion_interests"]) if obj.get("subregion_interests") is not None else None,
            "demography": AppendixInfo.from_dict(obj["demography"]) if obj.get("demography") is not None else None,
            "merged_data": AppendixInfo.from_dict(obj["merged_data"]) if obj.get("merged_data") is not None else None
        })
        return _obj


