# coding: utf-8

"""
    DataForSEO API documentation

    DataForSEO API is the starting point on your journey towards building powerful SEO software. With DataForSEO you can get all the data you need to build an efficient application while also saving your time and budget. DataForSEO API is using the REST technology for interchanging data between your application and our service. The data exchange is made through the widely used HTTP protocol, which allows applying our API to almost all programming languages.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dataforseo_client.api.keywords_data_api import KeywordsDataApi


class TestKeywordsDataApi(unittest.TestCase):
    """KeywordsDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeywordsDataApi()

    def tearDown(self) -> None:
        pass

    def test_bing_keyword_performance_live(self) -> None:
        """Test case for bing_keyword_performance_live

        """
        pass

    def test_bing_keyword_performance_task_get(self) -> None:
        """Test case for bing_keyword_performance_task_get

        """
        pass

    def test_bing_keyword_performance_task_post(self) -> None:
        """Test case for bing_keyword_performance_task_post

        """
        pass

    def test_bing_keyword_performance_tasks_ready(self) -> None:
        """Test case for bing_keyword_performance_tasks_ready

        """
        pass

    def test_bing_keywords_for_keywords_live(self) -> None:
        """Test case for bing_keywords_for_keywords_live

        """
        pass

    def test_bing_keywords_for_keywords_task_get(self) -> None:
        """Test case for bing_keywords_for_keywords_task_get

        """
        pass

    def test_bing_keywords_for_keywords_task_post(self) -> None:
        """Test case for bing_keywords_for_keywords_task_post

        """
        pass

    def test_bing_keywords_for_keywords_tasks_ready(self) -> None:
        """Test case for bing_keywords_for_keywords_tasks_ready

        """
        pass

    def test_bing_keywords_for_site_live(self) -> None:
        """Test case for bing_keywords_for_site_live

        """
        pass

    def test_bing_keywords_for_site_task_get(self) -> None:
        """Test case for bing_keywords_for_site_task_get

        """
        pass

    def test_bing_keywords_for_site_task_post(self) -> None:
        """Test case for bing_keywords_for_site_task_post

        """
        pass

    def test_bing_keywords_for_site_tasks_ready(self) -> None:
        """Test case for bing_keywords_for_site_tasks_ready

        """
        pass

    def test_bing_search_volume_live(self) -> None:
        """Test case for bing_search_volume_live

        """
        pass

    def test_bing_search_volume_task_get(self) -> None:
        """Test case for bing_search_volume_task_get

        """
        pass

    def test_bing_search_volume_task_post(self) -> None:
        """Test case for bing_search_volume_task_post

        """
        pass

    def test_bing_search_volume_tasks_ready(self) -> None:
        """Test case for bing_search_volume_tasks_ready

        """
        pass

    def test_dataforseo_trends_demography_live(self) -> None:
        """Test case for dataforseo_trends_demography_live

        """
        pass

    def test_dataforseo_trends_explore_live(self) -> None:
        """Test case for dataforseo_trends_explore_live

        """
        pass

    def test_dataforseo_trends_merged_data_live(self) -> None:
        """Test case for dataforseo_trends_merged_data_live

        """
        pass

    def test_dataforseo_trends_subregion_interests_live(self) -> None:
        """Test case for dataforseo_trends_subregion_interests_live

        """
        pass

    def test_google_ads_ad_traffic_by_keywords_live(self) -> None:
        """Test case for google_ads_ad_traffic_by_keywords_live

        """
        pass

    def test_google_ads_ad_traffic_by_keywords_task_get(self) -> None:
        """Test case for google_ads_ad_traffic_by_keywords_task_get

        """
        pass

    def test_google_ads_ad_traffic_by_keywords_task_post(self) -> None:
        """Test case for google_ads_ad_traffic_by_keywords_task_post

        """
        pass

    def test_google_ads_ad_traffic_by_keywords_tasks_ready(self) -> None:
        """Test case for google_ads_ad_traffic_by_keywords_tasks_ready

        """
        pass

    def test_google_ads_keywords_for_keywords_live(self) -> None:
        """Test case for google_ads_keywords_for_keywords_live

        """
        pass

    def test_google_ads_keywords_for_keywords_task_get(self) -> None:
        """Test case for google_ads_keywords_for_keywords_task_get

        """
        pass

    def test_google_ads_keywords_for_keywords_task_post(self) -> None:
        """Test case for google_ads_keywords_for_keywords_task_post

        """
        pass

    def test_google_ads_keywords_for_keywords_tasks_ready(self) -> None:
        """Test case for google_ads_keywords_for_keywords_tasks_ready

        """
        pass

    def test_google_ads_keywords_for_site_live(self) -> None:
        """Test case for google_ads_keywords_for_site_live

        """
        pass

    def test_google_ads_keywords_for_site_task_get(self) -> None:
        """Test case for google_ads_keywords_for_site_task_get

        """
        pass

    def test_google_ads_keywords_for_site_task_post(self) -> None:
        """Test case for google_ads_keywords_for_site_task_post

        """
        pass

    def test_google_ads_keywords_for_site_tasks_ready(self) -> None:
        """Test case for google_ads_keywords_for_site_tasks_ready

        """
        pass

    def test_google_ads_search_volume_live(self) -> None:
        """Test case for google_ads_search_volume_live

        """
        pass

    def test_google_ads_search_volume_task_get(self) -> None:
        """Test case for google_ads_search_volume_task_get

        """
        pass

    def test_google_ads_search_volume_task_post(self) -> None:
        """Test case for google_ads_search_volume_task_post

        """
        pass

    def test_google_ads_search_volume_tasks_ready(self) -> None:
        """Test case for google_ads_search_volume_tasks_ready

        """
        pass

    def test_google_ads_status(self) -> None:
        """Test case for google_ads_status

        """
        pass

    def test_google_trends_categories(self) -> None:
        """Test case for google_trends_categories

        """
        pass

    def test_google_trends_explore_live(self) -> None:
        """Test case for google_trends_explore_live

        """
        pass

    def test_google_trends_explore_task_get(self) -> None:
        """Test case for google_trends_explore_task_get

        """
        pass

    def test_google_trends_explore_task_post(self) -> None:
        """Test case for google_trends_explore_task_post

        """
        pass

    def test_google_trends_explore_tasks_ready(self) -> None:
        """Test case for google_trends_explore_tasks_ready

        """
        pass

    def test_keywords_data_bing_keyword_performance_locations_and_languages(self) -> None:
        """Test case for keywords_data_bing_keyword_performance_locations_and_languages

        """
        pass

    def test_keywords_data_bing_languages(self) -> None:
        """Test case for keywords_data_bing_languages

        """
        pass

    def test_keywords_data_bing_locations(self) -> None:
        """Test case for keywords_data_bing_locations

        """
        pass

    def test_keywords_data_dataforseo_trends_locations(self) -> None:
        """Test case for keywords_data_dataforseo_trends_locations

        """
        pass

    def test_keywords_data_dataforseo_trends_locations_country(self) -> None:
        """Test case for keywords_data_dataforseo_trends_locations_country

        """
        pass

    def test_keywords_data_errors(self) -> None:
        """Test case for keywords_data_errors

        """
        pass

    def test_keywords_data_google_ads_languages(self) -> None:
        """Test case for keywords_data_google_ads_languages

        """
        pass

    def test_keywords_data_google_ads_locations(self) -> None:
        """Test case for keywords_data_google_ads_locations

        """
        pass

    def test_keywords_data_google_trends_languages(self) -> None:
        """Test case for keywords_data_google_trends_languages

        """
        pass

    def test_keywords_data_google_trends_locations(self) -> None:
        """Test case for keywords_data_google_trends_locations

        """
        pass

    def test_keywords_data_google_trends_locations_country(self) -> None:
        """Test case for keywords_data_google_trends_locations_country

        """
        pass

    def test_keywords_data_id_list(self) -> None:
        """Test case for keywords_data_id_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
